//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SkyCar.Coeus.UIModel.SM.UIModel {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AROrgSupMerchantAuthorityDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class AROrgSupMerchantAuthorityDataSet : global::System.Data.DataSet {
        
        private AROrgSupMerchantAuthorityDataTable tableAROrgSupMerchantAuthority;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AROrgSupMerchantAuthorityDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AROrgSupMerchantAuthorityDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["AROrgSupMerchantAuthority"] != null)) {
                    base.Tables.Add(new AROrgSupMerchantAuthorityDataTable(ds.Tables["AROrgSupMerchantAuthority"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public AROrgSupMerchantAuthorityDataTable AROrgSupMerchantAuthority {
            get {
                return this.tableAROrgSupMerchantAuthority;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AROrgSupMerchantAuthorityDataSet cln = ((AROrgSupMerchantAuthorityDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["AROrgSupMerchantAuthority"] != null)) {
                    base.Tables.Add(new AROrgSupMerchantAuthorityDataTable(ds.Tables["AROrgSupMerchantAuthority"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableAROrgSupMerchantAuthority = ((AROrgSupMerchantAuthorityDataTable)(base.Tables["AROrgSupMerchantAuthority"]));
            if ((initTable == true)) {
                if ((this.tableAROrgSupMerchantAuthority != null)) {
                    this.tableAROrgSupMerchantAuthority.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AROrgSupMerchantAuthorityDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/AROrgSupMerchantAuthorityDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableAROrgSupMerchantAuthority = new AROrgSupMerchantAuthorityDataTable();
            base.Tables.Add(this.tableAROrgSupMerchantAuthority);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeAROrgSupMerchantAuthority() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AROrgSupMerchantAuthorityDataSet ds = new AROrgSupMerchantAuthorityDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void AROrgSupMerchantAuthorityRowChangeEventHandler(object sender, AROrgSupMerchantAuthorityRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class AROrgSupMerchantAuthorityDataTable : global::System.Data.TypedTableBase<AROrgSupMerchantAuthorityRow> {
            
            private global::System.Data.DataColumn columnASAH_ID;
            
            private global::System.Data.DataColumn columnASAH_ARMerchant_Code;
            
            private global::System.Data.DataColumn columnASAH_ARMerchant_Name;
            
            private global::System.Data.DataColumn columnASAH_AROrg_Code;
            
            private global::System.Data.DataColumn columnASAH_AROrg_Name;
            
            private global::System.Data.DataColumn columnASAH_AROrg_Contacter;
            
            private global::System.Data.DataColumn columnASAH_AROrg_Phone;
            
            private global::System.Data.DataColumn columnASAH_Remark;
            
            private global::System.Data.DataColumn columnASAH_IsValid;
            
            private global::System.Data.DataColumn columnASAH_CreatedBy;
            
            private global::System.Data.DataColumn columnASAH_CreatedTime;
            
            private global::System.Data.DataColumn columnASAH_UpdatedBy;
            
            private global::System.Data.DataColumn columnASAH_UpdatedTime;
            
            private global::System.Data.DataColumn columnASAH_VersionNo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityDataTable() {
                this.TableName = "AROrgSupMerchantAuthority";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AROrgSupMerchantAuthorityDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected AROrgSupMerchantAuthorityDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_IDColumn {
                get {
                    return this.columnASAH_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_ARMerchant_CodeColumn {
                get {
                    return this.columnASAH_ARMerchant_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_ARMerchant_NameColumn {
                get {
                    return this.columnASAH_ARMerchant_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_AROrg_CodeColumn {
                get {
                    return this.columnASAH_AROrg_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_AROrg_NameColumn {
                get {
                    return this.columnASAH_AROrg_Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_AROrg_ContacterColumn {
                get {
                    return this.columnASAH_AROrg_Contacter;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_AROrg_PhoneColumn {
                get {
                    return this.columnASAH_AROrg_Phone;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_RemarkColumn {
                get {
                    return this.columnASAH_Remark;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_IsValidColumn {
                get {
                    return this.columnASAH_IsValid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_CreatedByColumn {
                get {
                    return this.columnASAH_CreatedBy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_CreatedTimeColumn {
                get {
                    return this.columnASAH_CreatedTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_UpdatedByColumn {
                get {
                    return this.columnASAH_UpdatedBy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_UpdatedTimeColumn {
                get {
                    return this.columnASAH_UpdatedTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ASAH_VersionNoColumn {
                get {
                    return this.columnASAH_VersionNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityRow this[int index] {
                get {
                    return ((AROrgSupMerchantAuthorityRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrgSupMerchantAuthorityRowChangeEventHandler AROrgSupMerchantAuthorityRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrgSupMerchantAuthorityRowChangeEventHandler AROrgSupMerchantAuthorityRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrgSupMerchantAuthorityRowChangeEventHandler AROrgSupMerchantAuthorityRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrgSupMerchantAuthorityRowChangeEventHandler AROrgSupMerchantAuthorityRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddAROrgSupMerchantAuthorityRow(AROrgSupMerchantAuthorityRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityRow AddAROrgSupMerchantAuthorityRow(string ASAH_ID, string ASAH_ARMerchant_Code, string ASAH_ARMerchant_Name, string ASAH_AROrg_Code, string ASAH_AROrg_Name, string ASAH_AROrg_Contacter, string ASAH_AROrg_Phone, string ASAH_Remark, bool ASAH_IsValid, string ASAH_CreatedBy, System.DateTime ASAH_CreatedTime, string ASAH_UpdatedBy, System.DateTime ASAH_UpdatedTime, long ASAH_VersionNo) {
                AROrgSupMerchantAuthorityRow rowAROrgSupMerchantAuthorityRow = ((AROrgSupMerchantAuthorityRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ASAH_ID,
                        ASAH_ARMerchant_Code,
                        ASAH_ARMerchant_Name,
                        ASAH_AROrg_Code,
                        ASAH_AROrg_Name,
                        ASAH_AROrg_Contacter,
                        ASAH_AROrg_Phone,
                        ASAH_Remark,
                        ASAH_IsValid,
                        ASAH_CreatedBy,
                        ASAH_CreatedTime,
                        ASAH_UpdatedBy,
                        ASAH_UpdatedTime,
                        ASAH_VersionNo};
                rowAROrgSupMerchantAuthorityRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowAROrgSupMerchantAuthorityRow);
                return rowAROrgSupMerchantAuthorityRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                AROrgSupMerchantAuthorityDataTable cln = ((AROrgSupMerchantAuthorityDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new AROrgSupMerchantAuthorityDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnASAH_ID = base.Columns["ASAH_ID"];
                this.columnASAH_ARMerchant_Code = base.Columns["ASAH_ARMerchant_Code"];
                this.columnASAH_ARMerchant_Name = base.Columns["ASAH_ARMerchant_Name"];
                this.columnASAH_AROrg_Code = base.Columns["ASAH_AROrg_Code"];
                this.columnASAH_AROrg_Name = base.Columns["ASAH_AROrg_Name"];
                this.columnASAH_AROrg_Contacter = base.Columns["ASAH_AROrg_Contacter"];
                this.columnASAH_AROrg_Phone = base.Columns["ASAH_AROrg_Phone"];
                this.columnASAH_Remark = base.Columns["ASAH_Remark"];
                this.columnASAH_IsValid = base.Columns["ASAH_IsValid"];
                this.columnASAH_CreatedBy = base.Columns["ASAH_CreatedBy"];
                this.columnASAH_CreatedTime = base.Columns["ASAH_CreatedTime"];
                this.columnASAH_UpdatedBy = base.Columns["ASAH_UpdatedBy"];
                this.columnASAH_UpdatedTime = base.Columns["ASAH_UpdatedTime"];
                this.columnASAH_VersionNo = base.Columns["ASAH_VersionNo"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnASAH_ID = new global::System.Data.DataColumn("ASAH_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_ID);
                this.columnASAH_ARMerchant_Code = new global::System.Data.DataColumn("ASAH_ARMerchant_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_ARMerchant_Code);
                this.columnASAH_ARMerchant_Name = new global::System.Data.DataColumn("ASAH_ARMerchant_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_ARMerchant_Name);
                this.columnASAH_AROrg_Code = new global::System.Data.DataColumn("ASAH_AROrg_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_AROrg_Code);
                this.columnASAH_AROrg_Name = new global::System.Data.DataColumn("ASAH_AROrg_Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_AROrg_Name);
                this.columnASAH_AROrg_Contacter = new global::System.Data.DataColumn("ASAH_AROrg_Contacter", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_AROrg_Contacter);
                this.columnASAH_AROrg_Phone = new global::System.Data.DataColumn("ASAH_AROrg_Phone", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_AROrg_Phone);
                this.columnASAH_Remark = new global::System.Data.DataColumn("ASAH_Remark", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_Remark);
                this.columnASAH_IsValid = new global::System.Data.DataColumn("ASAH_IsValid", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_IsValid);
                this.columnASAH_CreatedBy = new global::System.Data.DataColumn("ASAH_CreatedBy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_CreatedBy);
                this.columnASAH_CreatedTime = new global::System.Data.DataColumn("ASAH_CreatedTime", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_CreatedTime);
                this.columnASAH_UpdatedBy = new global::System.Data.DataColumn("ASAH_UpdatedBy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_UpdatedBy);
                this.columnASAH_UpdatedTime = new global::System.Data.DataColumn("ASAH_UpdatedTime", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_UpdatedTime);
                this.columnASAH_VersionNo = new global::System.Data.DataColumn("ASAH_VersionNo", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAH_VersionNo);
                this.columnASAH_ID.MaxLength = 50;
                this.columnASAH_ARMerchant_Code.MaxLength = 50;
                this.columnASAH_ARMerchant_Name.MaxLength = 50;
                this.columnASAH_AROrg_Code.Caption = "DataColumn1";
                this.columnASAH_AROrg_Code.MaxLength = 50;
                this.columnASAH_AROrg_Name.Caption = "DataColumn2";
                this.columnASAH_AROrg_Name.MaxLength = 50;
                this.columnASAH_AROrg_Contacter.Caption = "DataColumn1";
                this.columnASAH_AROrg_Contacter.MaxLength = 50;
                this.columnASAH_AROrg_Phone.Caption = "DataColumn2";
                this.columnASAH_AROrg_Phone.MaxLength = 50;
                this.columnASAH_Remark.Caption = "DataColumn1";
                this.columnASAH_Remark.MaxLength = 200;
                this.columnASAH_IsValid.Caption = "DataColumn2";
                this.columnASAH_CreatedBy.Caption = "DataColumn1";
                this.columnASAH_CreatedBy.MaxLength = 50;
                this.columnASAH_CreatedTime.Caption = "DataColumn2";
                this.columnASAH_UpdatedBy.Caption = "DataColumn1";
                this.columnASAH_UpdatedBy.MaxLength = 50;
                this.columnASAH_UpdatedTime.Caption = "DataColumn2";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityRow NewAROrgSupMerchantAuthorityRow() {
                return ((AROrgSupMerchantAuthorityRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new AROrgSupMerchantAuthorityRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(AROrgSupMerchantAuthorityRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.AROrgSupMerchantAuthorityRowChanged != null)) {
                    this.AROrgSupMerchantAuthorityRowChanged(this, new AROrgSupMerchantAuthorityRowChangeEvent(((AROrgSupMerchantAuthorityRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.AROrgSupMerchantAuthorityRowChanging != null)) {
                    this.AROrgSupMerchantAuthorityRowChanging(this, new AROrgSupMerchantAuthorityRowChangeEvent(((AROrgSupMerchantAuthorityRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.AROrgSupMerchantAuthorityRowDeleted != null)) {
                    this.AROrgSupMerchantAuthorityRowDeleted(this, new AROrgSupMerchantAuthorityRowChangeEvent(((AROrgSupMerchantAuthorityRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.AROrgSupMerchantAuthorityRowDeleting != null)) {
                    this.AROrgSupMerchantAuthorityRowDeleting(this, new AROrgSupMerchantAuthorityRowChangeEvent(((AROrgSupMerchantAuthorityRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveAROrgSupMerchantAuthorityRow(AROrgSupMerchantAuthorityRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AROrgSupMerchantAuthorityDataSet ds = new AROrgSupMerchantAuthorityDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "AROrgSupMerchantAuthorityDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class AROrgSupMerchantAuthorityRow : global::System.Data.DataRow {
            
            private AROrgSupMerchantAuthorityDataTable tableAROrgSupMerchantAuthority;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AROrgSupMerchantAuthorityRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableAROrgSupMerchantAuthority = ((AROrgSupMerchantAuthorityDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_ID {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_ID”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_ARMerchant_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_ARMerchant_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_ARMerchant_Name {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_ARMerchant_Name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_AROrg_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_AROrg_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_AROrg_Name {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_AROrg_Name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_AROrg_Contacter {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_ContacterColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_AROrg_Contacter”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_ContacterColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_AROrg_Phone {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_PhoneColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_AROrg_Phone”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_PhoneColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_Remark {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_RemarkColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_Remark”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_RemarkColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool ASAH_IsValid {
                get {
                    try {
                        return ((bool)(this[this.tableAROrgSupMerchantAuthority.ASAH_IsValidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_IsValid”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_IsValidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_CreatedBy {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedByColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_CreatedBy”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedByColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime ASAH_CreatedTime {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_CreatedTime”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ASAH_UpdatedBy {
                get {
                    try {
                        return ((string)(this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedByColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_UpdatedBy”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedByColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime ASAH_UpdatedTime {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_UpdatedTime”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long ASAH_VersionNo {
                get {
                    try {
                        return ((long)(this[this.tableAROrgSupMerchantAuthority.ASAH_VersionNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrgSupMerchantAuthority”中列“ASAH_VersionNo”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrgSupMerchantAuthority.ASAH_VersionNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_IDNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_IDNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_ARMerchant_CodeNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_ARMerchant_CodeNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_ARMerchant_NameNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_ARMerchant_NameNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_ARMerchant_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_AROrg_CodeNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_AROrg_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_AROrg_CodeNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_AROrg_NameNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_AROrg_NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_AROrg_NameNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_AROrg_ContacterNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_AROrg_ContacterColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_AROrg_ContacterNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_ContacterColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_AROrg_PhoneNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_AROrg_PhoneColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_AROrg_PhoneNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_AROrg_PhoneColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_RemarkNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_RemarkColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_RemarkNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_RemarkColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_IsValidNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_IsValidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_IsValidNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_IsValidColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_CreatedByNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_CreatedByColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_CreatedByNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedByColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_CreatedTimeNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_CreatedTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_CreatedTimeNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_CreatedTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_UpdatedByNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_UpdatedByColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_UpdatedByNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedByColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_UpdatedTimeNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_UpdatedTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_UpdatedTimeNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_UpdatedTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsASAH_VersionNoNull() {
                return this.IsNull(this.tableAROrgSupMerchantAuthority.ASAH_VersionNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetASAH_VersionNoNull() {
                this[this.tableAROrgSupMerchantAuthority.ASAH_VersionNoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class AROrgSupMerchantAuthorityRowChangeEvent : global::System.EventArgs {
            
            private AROrgSupMerchantAuthorityRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityRowChangeEvent(AROrgSupMerchantAuthorityRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrgSupMerchantAuthorityRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591