//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SkyCar.Coeus.UIModel.Common {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AROrganizationDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class AROrganizationDataSet : global::System.Data.DataSet {
        
        private AROrganizationDataTable tableAROrganization;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AROrganizationDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AROrganizationDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["AROrganization"] != null)) {
                    base.Tables.Add(new AROrganizationDataTable(ds.Tables["AROrganization"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public AROrganizationDataTable AROrganization {
            get {
                return this.tableAROrganization;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AROrganizationDataSet cln = ((AROrganizationDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["AROrganization"] != null)) {
                    base.Tables.Add(new AROrganizationDataTable(ds.Tables["AROrganization"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableAROrganization = ((AROrganizationDataTable)(base.Tables["AROrganization"]));
            if ((initTable == true)) {
                if ((this.tableAROrganization != null)) {
                    this.tableAROrganization.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AROrganizationDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/AROrganizationDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableAROrganization = new AROrganizationDataTable();
            base.Tables.Add(this.tableAROrganization);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeAROrganization() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AROrganizationDataSet ds = new AROrganizationDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void AROrganizationRowChangeEventHandler(object sender, AROrganizationRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class AROrganizationDataTable : global::System.Data.TypedTableBase<AROrganizationRow> {
            
            private global::System.Data.DataColumn columnOrg_ID;
            
            private global::System.Data.DataColumn columnOrg_MCT_ID;
            
            private global::System.Data.DataColumn columnOrg_Code;
            
            private global::System.Data.DataColumn columnOrg_PlatformCode;
            
            private global::System.Data.DataColumn columnOrg_FullName;
            
            private global::System.Data.DataColumn columnOrg_ShortName;
            
            private global::System.Data.DataColumn columnOrg_Contacter;
            
            private global::System.Data.DataColumn columnOrg_TEL;
            
            private global::System.Data.DataColumn columnOrg_PhoneNo;
            
            private global::System.Data.DataColumn columnOrg_Prov_Code;
            
            private global::System.Data.DataColumn columnOrg_City_Code;
            
            private global::System.Data.DataColumn columnOrg_Dist_Code;
            
            private global::System.Data.DataColumn columnOrg_Addr;
            
            private global::System.Data.DataColumn columnOrg_Longitude;
            
            private global::System.Data.DataColumn columnOrg_Latitude;
            
            private global::System.Data.DataColumn columnOrg_MarkerTitle;
            
            private global::System.Data.DataColumn columnOrg_MarkerContent;
            
            private global::System.Data.DataColumn columnOrg_MainBrands;
            
            private global::System.Data.DataColumn columnOrg_MainProducts;
            
            private global::System.Data.DataColumn columnOrg_Remark;
            
            private global::System.Data.DataColumn columnOrg_IsValid;
            
            private global::System.Data.DataColumn columnOrg_CreatedBy;
            
            private global::System.Data.DataColumn columnOrg_CreatedTime;
            
            private global::System.Data.DataColumn columnOrg_UpdatedBy;
            
            private global::System.Data.DataColumn columnOrg_UpdatedTime;
            
            private global::System.Data.DataColumn columnOrg_VersionNo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationDataTable() {
                this.TableName = "AROrganization";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AROrganizationDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected AROrganizationDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_IDColumn {
                get {
                    return this.columnOrg_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_MCT_IDColumn {
                get {
                    return this.columnOrg_MCT_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_CodeColumn {
                get {
                    return this.columnOrg_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_PlatformCodeColumn {
                get {
                    return this.columnOrg_PlatformCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_FullNameColumn {
                get {
                    return this.columnOrg_FullName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_ShortNameColumn {
                get {
                    return this.columnOrg_ShortName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_ContacterColumn {
                get {
                    return this.columnOrg_Contacter;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_TELColumn {
                get {
                    return this.columnOrg_TEL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_PhoneNoColumn {
                get {
                    return this.columnOrg_PhoneNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_Prov_CodeColumn {
                get {
                    return this.columnOrg_Prov_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_City_CodeColumn {
                get {
                    return this.columnOrg_City_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_Dist_CodeColumn {
                get {
                    return this.columnOrg_Dist_Code;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_AddrColumn {
                get {
                    return this.columnOrg_Addr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_LongitudeColumn {
                get {
                    return this.columnOrg_Longitude;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_LatitudeColumn {
                get {
                    return this.columnOrg_Latitude;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_MarkerTitleColumn {
                get {
                    return this.columnOrg_MarkerTitle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_MarkerContentColumn {
                get {
                    return this.columnOrg_MarkerContent;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_MainBrandsColumn {
                get {
                    return this.columnOrg_MainBrands;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_MainProductsColumn {
                get {
                    return this.columnOrg_MainProducts;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_RemarkColumn {
                get {
                    return this.columnOrg_Remark;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_IsValidColumn {
                get {
                    return this.columnOrg_IsValid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_CreatedByColumn {
                get {
                    return this.columnOrg_CreatedBy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_CreatedTimeColumn {
                get {
                    return this.columnOrg_CreatedTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_UpdatedByColumn {
                get {
                    return this.columnOrg_UpdatedBy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_UpdatedTimeColumn {
                get {
                    return this.columnOrg_UpdatedTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Org_VersionNoColumn {
                get {
                    return this.columnOrg_VersionNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationRow this[int index] {
                get {
                    return ((AROrganizationRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrganizationRowChangeEventHandler AROrganizationRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrganizationRowChangeEventHandler AROrganizationRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrganizationRowChangeEventHandler AROrganizationRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AROrganizationRowChangeEventHandler AROrganizationRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddAROrganizationRow(AROrganizationRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationRow AddAROrganizationRow(
                        string Org_ID, 
                        string Org_MCT_ID, 
                        string Org_Code, 
                        string Org_PlatformCode, 
                        string Org_FullName, 
                        string Org_ShortName, 
                        string Org_Contacter, 
                        string Org_TEL, 
                        string Org_PhoneNo, 
                        string Org_Prov_Code, 
                        string Org_City_Code, 
                        string Org_Dist_Code, 
                        string Org_Addr, 
                        string Org_Longitude, 
                        string Org_Latitude, 
                        string Org_MarkerTitle, 
                        string Org_MarkerContent, 
                        string Org_MainBrands, 
                        string Org_MainProducts, 
                        string Org_Remark, 
                        bool Org_IsValid, 
                        string Org_CreatedBy, 
                        System.DateTime Org_CreatedTime, 
                        string Org_UpdatedBy, 
                        System.DateTime Org_UpdatedTime, 
                        long Org_VersionNo) {
                AROrganizationRow rowAROrganizationRow = ((AROrganizationRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Org_ID,
                        Org_MCT_ID,
                        Org_Code,
                        Org_PlatformCode,
                        Org_FullName,
                        Org_ShortName,
                        Org_Contacter,
                        Org_TEL,
                        Org_PhoneNo,
                        Org_Prov_Code,
                        Org_City_Code,
                        Org_Dist_Code,
                        Org_Addr,
                        Org_Longitude,
                        Org_Latitude,
                        Org_MarkerTitle,
                        Org_MarkerContent,
                        Org_MainBrands,
                        Org_MainProducts,
                        Org_Remark,
                        Org_IsValid,
                        Org_CreatedBy,
                        Org_CreatedTime,
                        Org_UpdatedBy,
                        Org_UpdatedTime,
                        Org_VersionNo};
                rowAROrganizationRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowAROrganizationRow);
                return rowAROrganizationRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                AROrganizationDataTable cln = ((AROrganizationDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new AROrganizationDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnOrg_ID = base.Columns["Org_ID"];
                this.columnOrg_MCT_ID = base.Columns["Org_MCT_ID"];
                this.columnOrg_Code = base.Columns["Org_Code"];
                this.columnOrg_PlatformCode = base.Columns["Org_PlatformCode"];
                this.columnOrg_FullName = base.Columns["Org_FullName"];
                this.columnOrg_ShortName = base.Columns["Org_ShortName"];
                this.columnOrg_Contacter = base.Columns["Org_Contacter"];
                this.columnOrg_TEL = base.Columns["Org_TEL"];
                this.columnOrg_PhoneNo = base.Columns["Org_PhoneNo"];
                this.columnOrg_Prov_Code = base.Columns["Org_Prov_Code"];
                this.columnOrg_City_Code = base.Columns["Org_City_Code"];
                this.columnOrg_Dist_Code = base.Columns["Org_Dist_Code"];
                this.columnOrg_Addr = base.Columns["Org_Addr"];
                this.columnOrg_Longitude = base.Columns["Org_Longitude"];
                this.columnOrg_Latitude = base.Columns["Org_Latitude"];
                this.columnOrg_MarkerTitle = base.Columns["Org_MarkerTitle"];
                this.columnOrg_MarkerContent = base.Columns["Org_MarkerContent"];
                this.columnOrg_MainBrands = base.Columns["Org_MainBrands"];
                this.columnOrg_MainProducts = base.Columns["Org_MainProducts"];
                this.columnOrg_Remark = base.Columns["Org_Remark"];
                this.columnOrg_IsValid = base.Columns["Org_IsValid"];
                this.columnOrg_CreatedBy = base.Columns["Org_CreatedBy"];
                this.columnOrg_CreatedTime = base.Columns["Org_CreatedTime"];
                this.columnOrg_UpdatedBy = base.Columns["Org_UpdatedBy"];
                this.columnOrg_UpdatedTime = base.Columns["Org_UpdatedTime"];
                this.columnOrg_VersionNo = base.Columns["Org_VersionNo"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnOrg_ID = new global::System.Data.DataColumn("Org_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_ID);
                this.columnOrg_MCT_ID = new global::System.Data.DataColumn("Org_MCT_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_MCT_ID);
                this.columnOrg_Code = new global::System.Data.DataColumn("Org_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Code);
                this.columnOrg_PlatformCode = new global::System.Data.DataColumn("Org_PlatformCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_PlatformCode);
                this.columnOrg_FullName = new global::System.Data.DataColumn("Org_FullName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_FullName);
                this.columnOrg_ShortName = new global::System.Data.DataColumn("Org_ShortName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_ShortName);
                this.columnOrg_Contacter = new global::System.Data.DataColumn("Org_Contacter", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Contacter);
                this.columnOrg_TEL = new global::System.Data.DataColumn("Org_TEL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_TEL);
                this.columnOrg_PhoneNo = new global::System.Data.DataColumn("Org_PhoneNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_PhoneNo);
                this.columnOrg_Prov_Code = new global::System.Data.DataColumn("Org_Prov_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Prov_Code);
                this.columnOrg_City_Code = new global::System.Data.DataColumn("Org_City_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_City_Code);
                this.columnOrg_Dist_Code = new global::System.Data.DataColumn("Org_Dist_Code", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Dist_Code);
                this.columnOrg_Addr = new global::System.Data.DataColumn("Org_Addr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Addr);
                this.columnOrg_Longitude = new global::System.Data.DataColumn("Org_Longitude", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Longitude);
                this.columnOrg_Latitude = new global::System.Data.DataColumn("Org_Latitude", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Latitude);
                this.columnOrg_MarkerTitle = new global::System.Data.DataColumn("Org_MarkerTitle", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_MarkerTitle);
                this.columnOrg_MarkerContent = new global::System.Data.DataColumn("Org_MarkerContent", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_MarkerContent);
                this.columnOrg_MainBrands = new global::System.Data.DataColumn("Org_MainBrands", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_MainBrands);
                this.columnOrg_MainProducts = new global::System.Data.DataColumn("Org_MainProducts", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_MainProducts);
                this.columnOrg_Remark = new global::System.Data.DataColumn("Org_Remark", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_Remark);
                this.columnOrg_IsValid = new global::System.Data.DataColumn("Org_IsValid", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_IsValid);
                this.columnOrg_CreatedBy = new global::System.Data.DataColumn("Org_CreatedBy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_CreatedBy);
                this.columnOrg_CreatedTime = new global::System.Data.DataColumn("Org_CreatedTime", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_CreatedTime);
                this.columnOrg_UpdatedBy = new global::System.Data.DataColumn("Org_UpdatedBy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_UpdatedBy);
                this.columnOrg_UpdatedTime = new global::System.Data.DataColumn("Org_UpdatedTime", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_UpdatedTime);
                this.columnOrg_VersionNo = new global::System.Data.DataColumn("Org_VersionNo", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrg_VersionNo);
                this.columnOrg_ID.MaxLength = 50;
                this.columnOrg_MCT_ID.Caption = "DataColumn1";
                this.columnOrg_MCT_ID.MaxLength = 50;
                this.columnOrg_Code.Caption = "DataColumn2";
                this.columnOrg_Code.MaxLength = 50;
                this.columnOrg_PlatformCode.Caption = "DataColumn1";
                this.columnOrg_PlatformCode.MaxLength = 50;
                this.columnOrg_FullName.Caption = "DataColumn2";
                this.columnOrg_FullName.MaxLength = 200;
                this.columnOrg_ShortName.Caption = "DataColumn1";
                this.columnOrg_ShortName.MaxLength = 50;
                this.columnOrg_Contacter.Caption = "DataColumn2";
                this.columnOrg_Contacter.MaxLength = 200;
                this.columnOrg_TEL.Caption = "DataColumn1";
                this.columnOrg_TEL.MaxLength = 50;
                this.columnOrg_PhoneNo.Caption = "DataColumn2";
                this.columnOrg_PhoneNo.MaxLength = 200;
                this.columnOrg_Prov_Code.Caption = "DataColumn1";
                this.columnOrg_Prov_Code.MaxLength = 50;
                this.columnOrg_City_Code.Caption = "DataColumn2";
                this.columnOrg_City_Code.MaxLength = 50;
                this.columnOrg_Dist_Code.Caption = "DataColumn1";
                this.columnOrg_Dist_Code.MaxLength = 50;
                this.columnOrg_Addr.Caption = "DataColumn2";
                this.columnOrg_Longitude.Caption = "DataColumn2";
                this.columnOrg_Latitude.Caption = "DataColumn2";
                this.columnOrg_Latitude.MaxLength = 50;
                this.columnOrg_MarkerTitle.Caption = "DataColumn2";
                this.columnOrg_MarkerTitle.MaxLength = 50;
                this.columnOrg_MarkerContent.Caption = "DataColumn2";
                this.columnOrg_MarkerContent.MaxLength = 50;
                this.columnOrg_MainBrands.Caption = "DataColumn2";
                this.columnOrg_MainBrands.MaxLength = 500;
                this.columnOrg_MainProducts.Caption = "DataColumn2";
                this.columnOrg_MainProducts.MaxLength = 500;
                this.columnOrg_Remark.Caption = "DataColumn2";
                this.columnOrg_Remark.MaxLength = 200;
                this.columnOrg_IsValid.Caption = "DataColumn2";
                this.columnOrg_CreatedBy.Caption = "DataColumn2";
                this.columnOrg_CreatedBy.MaxLength = 50;
                this.columnOrg_CreatedTime.Caption = "DataColumn2";
                this.columnOrg_UpdatedBy.Caption = "DataColumn2";
                this.columnOrg_UpdatedBy.MaxLength = 50;
                this.columnOrg_UpdatedTime.Caption = "DataColumn2";
                this.columnOrg_VersionNo.Caption = "DataColumn2";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationRow NewAROrganizationRow() {
                return ((AROrganizationRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new AROrganizationRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(AROrganizationRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.AROrganizationRowChanged != null)) {
                    this.AROrganizationRowChanged(this, new AROrganizationRowChangeEvent(((AROrganizationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.AROrganizationRowChanging != null)) {
                    this.AROrganizationRowChanging(this, new AROrganizationRowChangeEvent(((AROrganizationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.AROrganizationRowDeleted != null)) {
                    this.AROrganizationRowDeleted(this, new AROrganizationRowChangeEvent(((AROrganizationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.AROrganizationRowDeleting != null)) {
                    this.AROrganizationRowDeleting(this, new AROrganizationRowChangeEvent(((AROrganizationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveAROrganizationRow(AROrganizationRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AROrganizationDataSet ds = new AROrganizationDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "AROrganizationDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class AROrganizationRow : global::System.Data.DataRow {
            
            private AROrganizationDataTable tableAROrganization;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AROrganizationRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableAROrganization = ((AROrganizationDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_ID {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_ID”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_MCT_ID {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_MCT_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_MCT_ID”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_MCT_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_PlatformCode {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_PlatformCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_PlatformCode”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_PlatformCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_FullName {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_FullNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_FullName”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_FullNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_ShortName {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_ShortNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_ShortName”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_ShortNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Contacter {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_ContacterColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Contacter”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_ContacterColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_TEL {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_TELColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_TEL”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_TELColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_PhoneNo {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_PhoneNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_PhoneNo”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_PhoneNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Prov_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_Prov_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Prov_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_Prov_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_City_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_City_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_City_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_City_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Dist_Code {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_Dist_CodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Dist_Code”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_Dist_CodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Addr {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_AddrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Addr”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_AddrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Longitude {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_LongitudeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Longitude”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_LongitudeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Latitude {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_LatitudeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Latitude”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_LatitudeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_MarkerTitle {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_MarkerTitleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_MarkerTitle”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_MarkerTitleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_MarkerContent {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_MarkerContentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_MarkerContent”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_MarkerContentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_MainBrands {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_MainBrandsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_MainBrands”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_MainBrandsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_MainProducts {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_MainProductsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_MainProducts”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_MainProductsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_Remark {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_RemarkColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_Remark”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_RemarkColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Org_IsValid {
                get {
                    try {
                        return ((bool)(this[this.tableAROrganization.Org_IsValidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_IsValid”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_IsValidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_CreatedBy {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_CreatedByColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_CreatedBy”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_CreatedByColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Org_CreatedTime {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAROrganization.Org_CreatedTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_CreatedTime”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_CreatedTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Org_UpdatedBy {
                get {
                    try {
                        return ((string)(this[this.tableAROrganization.Org_UpdatedByColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_UpdatedBy”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_UpdatedByColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Org_UpdatedTime {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAROrganization.Org_UpdatedTimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_UpdatedTime”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_UpdatedTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long Org_VersionNo {
                get {
                    try {
                        return ((long)(this[this.tableAROrganization.Org_VersionNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AROrganization”中列“Org_VersionNo”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAROrganization.Org_VersionNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_IDNull() {
                return this.IsNull(this.tableAROrganization.Org_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_IDNull() {
                this[this.tableAROrganization.Org_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_MCT_IDNull() {
                return this.IsNull(this.tableAROrganization.Org_MCT_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_MCT_IDNull() {
                this[this.tableAROrganization.Org_MCT_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_CodeNull() {
                return this.IsNull(this.tableAROrganization.Org_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_CodeNull() {
                this[this.tableAROrganization.Org_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_PlatformCodeNull() {
                return this.IsNull(this.tableAROrganization.Org_PlatformCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_PlatformCodeNull() {
                this[this.tableAROrganization.Org_PlatformCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_FullNameNull() {
                return this.IsNull(this.tableAROrganization.Org_FullNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_FullNameNull() {
                this[this.tableAROrganization.Org_FullNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_ShortNameNull() {
                return this.IsNull(this.tableAROrganization.Org_ShortNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_ShortNameNull() {
                this[this.tableAROrganization.Org_ShortNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_ContacterNull() {
                return this.IsNull(this.tableAROrganization.Org_ContacterColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_ContacterNull() {
                this[this.tableAROrganization.Org_ContacterColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_TELNull() {
                return this.IsNull(this.tableAROrganization.Org_TELColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_TELNull() {
                this[this.tableAROrganization.Org_TELColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_PhoneNoNull() {
                return this.IsNull(this.tableAROrganization.Org_PhoneNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_PhoneNoNull() {
                this[this.tableAROrganization.Org_PhoneNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_Prov_CodeNull() {
                return this.IsNull(this.tableAROrganization.Org_Prov_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_Prov_CodeNull() {
                this[this.tableAROrganization.Org_Prov_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_City_CodeNull() {
                return this.IsNull(this.tableAROrganization.Org_City_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_City_CodeNull() {
                this[this.tableAROrganization.Org_City_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_Dist_CodeNull() {
                return this.IsNull(this.tableAROrganization.Org_Dist_CodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_Dist_CodeNull() {
                this[this.tableAROrganization.Org_Dist_CodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_AddrNull() {
                return this.IsNull(this.tableAROrganization.Org_AddrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_AddrNull() {
                this[this.tableAROrganization.Org_AddrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_LongitudeNull() {
                return this.IsNull(this.tableAROrganization.Org_LongitudeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_LongitudeNull() {
                this[this.tableAROrganization.Org_LongitudeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_LatitudeNull() {
                return this.IsNull(this.tableAROrganization.Org_LatitudeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_LatitudeNull() {
                this[this.tableAROrganization.Org_LatitudeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_MarkerTitleNull() {
                return this.IsNull(this.tableAROrganization.Org_MarkerTitleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_MarkerTitleNull() {
                this[this.tableAROrganization.Org_MarkerTitleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_MarkerContentNull() {
                return this.IsNull(this.tableAROrganization.Org_MarkerContentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_MarkerContentNull() {
                this[this.tableAROrganization.Org_MarkerContentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_MainBrandsNull() {
                return this.IsNull(this.tableAROrganization.Org_MainBrandsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_MainBrandsNull() {
                this[this.tableAROrganization.Org_MainBrandsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_MainProductsNull() {
                return this.IsNull(this.tableAROrganization.Org_MainProductsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_MainProductsNull() {
                this[this.tableAROrganization.Org_MainProductsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_RemarkNull() {
                return this.IsNull(this.tableAROrganization.Org_RemarkColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_RemarkNull() {
                this[this.tableAROrganization.Org_RemarkColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_IsValidNull() {
                return this.IsNull(this.tableAROrganization.Org_IsValidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_IsValidNull() {
                this[this.tableAROrganization.Org_IsValidColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_CreatedByNull() {
                return this.IsNull(this.tableAROrganization.Org_CreatedByColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_CreatedByNull() {
                this[this.tableAROrganization.Org_CreatedByColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_CreatedTimeNull() {
                return this.IsNull(this.tableAROrganization.Org_CreatedTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_CreatedTimeNull() {
                this[this.tableAROrganization.Org_CreatedTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_UpdatedByNull() {
                return this.IsNull(this.tableAROrganization.Org_UpdatedByColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_UpdatedByNull() {
                this[this.tableAROrganization.Org_UpdatedByColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_UpdatedTimeNull() {
                return this.IsNull(this.tableAROrganization.Org_UpdatedTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_UpdatedTimeNull() {
                this[this.tableAROrganization.Org_UpdatedTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrg_VersionNoNull() {
                return this.IsNull(this.tableAROrganization.Org_VersionNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrg_VersionNoNull() {
                this[this.tableAROrganization.Org_VersionNoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class AROrganizationRowChangeEvent : global::System.EventArgs {
            
            private AROrganizationRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationRowChangeEvent(AROrganizationRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AROrganizationRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591